name: Update Problem Count

on:
  push:
    branches: [ main ]

jobs:
  update-count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Count problems
        run: |
          COUNT=$(grep -E '^\| [0-9]+' README.md | wc -l)
          echo "Detected $COUNT problems."
          sed -i "s/<!--PROBLEM_COUNT_START-->.*<!--PROBLEM_COUNT_END-->/<!--PROBLEM_COUNT_START-->$COUNT<!--PROBLEM_COUNT_END-->/" README.md
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update problem count: $COUNT" || echo "No changes"
          git push
